version: "3"
services:
  benchmarkapp:
    image: "nclcloudcomputing/javabenchmarkapp"
    deploy: 
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "8080:8080"
    environment: 
      ENV_KEY: ENV_VALUE

  swarm: 
    image: dockersamples/visualizer
    deploy: 
      replicas: 1 
      placement:
        constraints:
          - "node.role==manager"
    ports: 
      - "8072:8080"

  cAdvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    deploy: 
      replicas: 1 
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "8888:8080"
 
  locust:
    image: locustio/locust
    deploy: 
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "8082:8089"
  
  mongo:
    image: mongo
    deploy: 
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  




